### ISSUE TITLE
Protótipos de tela

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/StarScience#22]
Construir o protótipo de todas as telas necessárias para a nova versão do StarScience.

**Comment by VCLM** [comment]
Protótipos de Interface com o Usuário Atualizado.

[Link para os  protótipos.](https://www.figma.com/file/WUxi12rpaoobJRdxDoIxH9/StarScience?node-id=37%3A2&t=45LnqoBcnLvXsWKh-0)

**Comment by alessandrojsouza** [comment]
Atualizar o modelo segundo os novos requisitos tratados em reunião.
