### ISSUE TITLE
Diagrama de contexto

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/StarScience#28]
Construir o diagrama de contexto usando a sintaxe do C4 Model (https://c4model.com/)

**Comment by JoanaFernandes1998** [comment]
[https://drive.google.com/file/d/1SJ3_wb8N9WnB_lMkjIDqJZwd76umgR8Z/view?usp=sharing](url)

**Comment by JoanaFernandes1998** [comment]
https://drive.google.com/file/d/1SJ3_wb8N9WnB_lMkjIDqJZwd76umgR8Z/view?usp=sharing
