### ISSUE TITLE
Diagrama de Componentes

### ISSUE THREAD

**Issue by alessandrojsouza** [tads-cnat/StarScience#31]
Construir o diagrama de componente do projeto usando a sintaxe do [c4model](https://c4model.com/).

**Comment by JoanaFernandes1998** [comment]
Diagrama de Component:

[https://drive.google.com/file/d/1SJ3_wb8N9WnB_lMkjIDqJZwd76umgR8Z/view?usp=sharing](url)

**Comment by JoanaFernandes1998** [comment]
https://app.diagrams.net/#G1SJ3_wb8N9WnB_lMkjIDqJZwd76umgR8Z#%7B%22pageId%22%3A%22yeX1yha-NNqh4WTSywhu%22%7D
